version: '3.7'
services:
  frontend:
    build: ./frontend
    command: sh -c "npm run dev"
    ports:
    - '8080:8080'
    volumes:
    - './frontend:/app'
    environment:
      HOST: 0.0.0.0

  backend:
    build: .
    command:  python -u main.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - .:/data/db
    